export const SHOW_MODAL = "REACT/CUSTOM_MODAL/SHOW_MODAL";
export const HIDE_MODAL = "REACT/CUSTOM_MODAL/HIDE_MODAL";

export const SAVE_CHANGE_DATA = "REACT/CUSTOM_MODAL/SAVE_CHANGE_DATA";
export const DELETE_ITEM_DATA = "REACT/CUSTOM_MODAL/DELETE_ITEM_DATA";